<?php

/**
 * Copyright (c) 2017-present, Emile Silas Sare
 *
 * This file is part of OZone package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace OZONE\Tests\Forms;

use InvalidArgumentException;
use OZONE\Core\Forms\Form;
use OZONE\Core\Forms\FormRegistry;
use PHPUnit\Framework\TestCase;

/**
 * Class FormRegistryTest.
 *
 * Tests for {@see FormRegistry} and the related {@see Form::key()} / {@see Form::register()} API.
 *
 * @internal
 *
 * @coversNothing
 */
final class FormRegistryTest extends TestCase
{
	protected function setUp(): void
	{
		FormRegistry::clear();
	}

	// -----------------------------------------------------------------------
	// FormRegistry core API
	// -----------------------------------------------------------------------

	public function testRegisterAndGet(): void
	{
		$form = new Form();
		FormRegistry::register('my.form', $form);

		self::assertSame($form, FormRegistry::get('my.form'));
	}

	public function testGetReturnsNullForUnknownKey(): void
	{
		self::assertNull(FormRegistry::get('unknown'));
	}

	public function testAllReturnsRegisteredForms(): void
	{
		$a = new Form();
		$b = new Form();
		FormRegistry::register('form.a', $a);
		FormRegistry::register('form.b', $b);

		self::assertSame(['form.a' => $a, 'form.b' => $b], FormRegistry::all());
	}

	public function testRegisterOverwritesPrevious(): void
	{
		$first  = new Form();
		$second = new Form();
		FormRegistry::register('dupe', $first);
		FormRegistry::register('dupe', $second);

		self::assertSame($second, FormRegistry::get('dupe'));
	}

	public function testClearEmptiesRegistry(): void
	{
		FormRegistry::register('x', new Form());
		FormRegistry::clear();

		self::assertSame([], FormRegistry::all());
		self::assertNull(FormRegistry::get('x'));
	}

	public function testUnregister(): void
	{
		$form = new Form();
		FormRegistry::register('test.form', $form);

		self::assertSame($form, FormRegistry::get('test.form'));

		FormRegistry::unregister('test.form');

		self::assertNull(FormRegistry::get('test.form'));
	}

	public function testUnregisterNonExistentIsNoOp(): void
	{
		// Should not throw.
		FormRegistry::unregister('does.not.exist');

		self::assertNull(FormRegistry::get('does.not.exist'));
	}

	// -----------------------------------------------------------------------
	// Form::key()
	// -----------------------------------------------------------------------

	public function testKeyAutoGeneratedOnConstruction(): void
	{
		$form = new Form();

		self::assertNotEmpty($form->getKey());
		self::assertStringStartsWith('oz:form:auto:', $form->getKey());
	}

	public function testAutoGeneratedKeysAreUnique(): void
	{
		$a = new Form();
		$b = new Form();

		self::assertNotSame($a->getKey(), $b->getKey());
	}

	public function testKeyEmptyStringThrows(): void
	{
		$this->expectException(InvalidArgumentException::class);

		(new Form())->key('');
	}

	public function testKeyWhitespaceOnlyStringThrows(): void
	{
		$this->expectException(InvalidArgumentException::class);

		(new Form())->key('   ');
	}

	public function testKeyReturnsSelf(): void
	{
		$form   = new Form();
		$result = $form->key('some.key');

		self::assertSame($form, $result);
	}

	public function testKeyIdempotentSameKey(): void
	{
		$form = new Form();
		$form->register();
		$form->key('my.form');
		$form->key('my.form'); // second call with same key — no-op

		self::assertSame('my.form', $form->getKey());
		self::assertSame($form, FormRegistry::get('my.form'));
	}

	public function testKeyChangeWhenNotRegisteredDoesNotTouchRegistry(): void
	{
		$form = new Form();
		$old  = $form->getKey();

		$form->key('explicit.key');

		// Not registered yet — old auto-key was never in the registry.
		self::assertNull(FormRegistry::get($old));
		self::assertNull(FormRegistry::get('explicit.key'));
	}

	public function testKeyChangeUnregistersOldKeyWhenRegistered(): void
	{
		$form = new Form();
		$form->register();
		$form->key('old.key');

		$form->key('new.key');

		self::assertNull(FormRegistry::get('old.key'));
	}

	public function testKeyChangeRegistersNewKeyWhenAlreadyRegistered(): void
	{
		$form = new Form();
		$form->register();
		$form->key('old.key');

		$form->key('new.key');

		self::assertSame($form, FormRegistry::get('new.key'));
		self::assertSame('new.key', $form->getKey());
	}

	public function testKeyAutoThenOverrideMovesRegistration(): void
	{
		$form    = new Form();
		$autoKey = $form->register()->getKey();

		$form->key('explicit.key');

		self::assertNull(FormRegistry::get($autoKey));
		self::assertSame($form, FormRegistry::get('explicit.key'));
		self::assertSame('explicit.key', $form->getKey());
	}

	// -----------------------------------------------------------------------
	// Form::register()
	// -----------------------------------------------------------------------

	public function testRegisterAddsFormToRegistry(): void
	{
		$form = new Form();
		$key  = $form->getKey();

		$form->register();

		self::assertSame($form, FormRegistry::get($key));
	}

	public function testRegisterReturnsSelf(): void
	{
		$form   = new Form();
		$result = $form->register();

		self::assertSame($form, $result);
	}

	public function testRegisterIsIdempotent(): void
	{
		$form = new Form();
		$form->register();
		$form->register(); // second call must not throw or add a duplicate

		self::assertCount(1, FormRegistry::all());
		self::assertSame($form, FormRegistry::get($form->getKey()));
	}
}
